---
title: "TDA_flask_exp"
author: "Erik Bjurström"
date: "2023-03-08"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries, echo=F}
#Loads all the libraries needed for analysis
library(DESeq2,warn.conflicts = F)
library(tidyverse,warn.conflicts = F)
library(tximport,warn.conflicts = F)
library(ashr)
library(knitr,warn.conflicts = F)
```

```{r Function scripts, echo = F}
# Imports all the R functions in this Rmd from subdir "R_scripts"
file.sources = list.files("./scripts",pattern = "*.R",full.names = T)
sapply(file.sources, source, .GlobalEnv)
```

```{r Extract count data, echo=F}
# Finds all folders in /data that ends with "salmon", i.e. the folders with the
# quant.sf files which contains counts mapped to genes.

samples_3 <- list.files(path = "./data/Exp3", full.names = T, pattern = "[e-t]$")
files_3 <- file.path(samples_3, "quant.sf")

# Names each entry in "files" to the sample name
# e.g. ./data/T1_post.salmon/quant.sf -> T1_post
names(files_3) <- str_replace(samples_3, "./data/Exp3/","")

# "salmon_tx2gene.tsv" contains the Gene_stable_ID and Gene_name of each gene
tx2gene <- read.delim("./data/db/salmon_tx2gene.tsv", sep = "\t", quote = "")

# Imports count data from each quant.sf and names each gene using 
# "salmon_tx2gene.tsv"
txi_3 <- tximport(files_3, type="salmon", 
                tx2gene = tx2gene[,c("tx_id", "ensgene", "symbol")], 
                countsFromAbundance = "lengthScaledTPM")

# Rounds counts to integers 
data <- txi_3$counts %>% 
  round() %>% 
  data.frame()
```

```{r Loads meta data}
# Load sample info, used when contrasting samples using DESeq2
meta_3 <- read.csv("./data/Exp3/Sample_info3.csv", sep = ",", quote ="", 
                 row.names = colnames(txi_3$counts)) %>% 
                      dplyr::select(c("Strain", "Phase"))

```

```{r Verify meta, echo=F}
# Verifies that all column names in the data matches the row names in the
# metadata file

all(colnames(txi_3$counts) %in% rownames(meta_3))
all(colnames(txi_3$counts) == rownames(meta_3))
```

```{r Outlier removal}
outliers_3 = c("R4Pre")
files_clean_3 <- files_3[!(names(files_3) %in% outliers_3)]

txi_clean_3 <- tximport(files_clean_3, type="salmon", 
                tx2gene = tx2gene[,c("tx_id", "ensgene", "symbol")], 
                countsFromAbundance = "lengthScaledTPM")

meta_clean_3 <- meta_3[!(rownames(meta_3) %in% outliers_3),]


all(colnames(txi_clean_3$counts) %in% rownames(meta_clean_3))
all(colnames(txi_clean_3$counts) == rownames(meta_clean_3))
```

```{r DDS, echo=F}
# Create DESeq2Dataset object
dds_3 <- DESeqDataSetFromTximport(txi_clean_3, colData = meta_clean_3, design = ~Strain + Phase + Strain:Phase)
dds_3$group <- factor(paste0(dds_3$Strain, dds_3$Phase))
design(dds_3) <- ~group
dds_3 <- estimateSizeFactors(dds_3)

# Uses Median of Ratios method
normalized_counts_3 <- counts(dds_3, normalized = T)
normalized_counts_3 <- normalized_counts_3[,c(2,4,6,9,11,13,15,17,19,21,23,1,3,5,7,8,10,12,14,16,18,20,22)]
not_normalized_counts_3 <- counts(dds_3, normalized = F)
not_normalized_counts_3 <- not_normalized_counts_3[,c(2,4,6,9,11,13,15,17,19,21,23,1,3,5,7,8,10,12,14,16,18,20,22)]
```

```{r}
# Loads a file with Gene_stable_ID, Gene_names, and Gene_description
gene_description <- read.csv("./data/db/gene_names.txt",header = TRUE, sep = "\t", 
                             quote = "")
# Makes a tibble of the normalized counts
normalized_counts_tb_3 <- normalized_counts_3 %>%
  data.frame() %>%
  rownames_to_column(var="Gene_stable_ID") %>% 
  as_tibble()

# Adds gene name and description to the normalized counts
normalized_counts_nice_3 <- nicefy_gene_results(normalized_counts_tb_3, gene_description)
```

```{r}
# Script to save a table of unnormalized counts.
raw_counts_3 <- not_normalized_counts_3 %>% as.data.frame()

raw_counts_tb_3 <- raw_counts_3 %>%
  data.frame() %>%
  rownames_to_column(var="Gene_stable_ID") %>% 
  as_tibble()

# Adds gene name and description to the raw counts
raw_counts_nice_3 <- nicefy_gene_results(raw_counts_tb_3, gene_description)
```

```{r}
# Runs DESeq2 on the dds object
dds_3 <- DESeq(dds_3)
```

```{r, echo=F}
# Performs lfc-shrinkage on the result tables using ashr
res_table_log_3 <- lfcShrink(dds_3, 
                               contrast = c("group", "tda1∆log", 
                                            "Referencelog"), type ="ashr")
res_table_PDS_3 <- lfcShrink(dds_3, 
                               contrast = c("group", "tda1∆PDS", 
                                            "ReferencePDS"), type ="ashr")

res_table_Ref_3 <- lfcShrink(dds_3, 
                          contrast = c("group", "ReferencePDS", 
                                       "Referencelog"), type ="ashr")
res_table_TDA_3 <- lfcShrink(dds_3, 
                           contrast = c("group", "tda1∆PDS", 
                                        "tda1∆log"), type ="ashr")

# Prints the summary of the results tables
summary(res_table_log_3, alpha = 0.05)
summary(res_table_PDS_3, alpha = 0.05)
summary(res_table_Ref_3, alpha = 0.05)
summary(res_table_TDA_3, alpha = 0.05)
```
  
```{r}
# Makes a tibble of only significant genes (padj < padj.cutoff)
padj.cutoff <- 0.05

res_table_log_tb_3 <- res_table_log_3 %>%
  data.frame() %>%
  rownames_to_column(var="Gene_stable_ID") %>% 
  as_tibble()

sig_log_3 <- res_table_log_tb_3 %>% 
  filter(padj < padj.cutoff)

# Makes a tibble of only significant genes, RefvsTDA1 during PDS
res_table_PDS_tb_3 <- res_table_PDS_3 %>%
  data.frame() %>%
  rownames_to_column(var="Gene_stable_ID") %>% 
  as_tibble()

sig_PDS_3 <- res_table_PDS_tb_3 %>% 
  filter(padj < padj.cutoff)

# Makes a tibble of significant genes glucuse vs PDS in Ref
res_table_Ref_tb_3 <- res_table_Ref_3 %>%
  data.frame() %>%
  rownames_to_column(var="Gene_stable_ID") %>% 
  as_tibble()

sig_Ref_3 <- res_table_Ref_tb_3 %>% 
  filter(padj < padj.cutoff)

# Makes a tibble of siginifcant genes log-phase vs PDS-phase for TDA1
res_table_TDA_tb_3 <- res_table_TDA_3 %>%
  data.frame() %>%
  rownames_to_column(var="Gene_stable_ID") %>% 
  as_tibble()

sig_TDA_3 <- res_table_TDA_tb_3 %>% 
  filter(padj < padj.cutoff)
```

```{r}
sig_log_nice_3 <- nicefy_gene_results(sig_log_3, gene_description)
sig_PDS_nice_3 <- nicefy_gene_results(sig_PDS_3, gene_description)
sig_Ref_nice_3 <- nicefy_gene_results(sig_Ref_3, gene_description)
sig_TDA_nice_3 <- nicefy_gene_results(sig_TDA_3, gene_description)

res_table_log_nice_3 <- nicefy_gene_results(res_table_log_tb_3, gene_description)
res_table_PDS_nice_3 <- nicefy_gene_results(res_table_PDS_tb_3, gene_description)
res_table_Ref_nice_3 <- nicefy_gene_results(res_table_Ref_tb_3, gene_description)
res_table_TDA_nice_3 <- nicefy_gene_results(res_table_TDA_tb_3, gene_description)
```

```{r}
save_r_object(raw_counts_nice_3, "./r_objects/Exp3/")
save_r_object(normalized_counts_3, "./r_objects/Exp3/")
save_r_object(normalized_counts_nice_3, "./r_objects/Exp3/")

save_r_object(res_table_log_nice_3, "./r_objects/Exp3/")
save_r_object(res_table_PDS_nice_3, "./r_objects/Exp3/")
save_r_object(res_table_Ref_nice_3, "./r_objects/Exp3/")
save_r_object(res_table_TDA_nice_3, "./r_objects/Exp3/")

save_r_object(sig_log_nice_3, "./r_objects/Exp3/")
save_r_object(sig_PDS_nice_3, "./r_objects/Exp3/")
save_r_object(sig_Ref_nice_3, "./r_objects/Exp3/")
save_r_object(sig_TDA_nice_3, "./r_objects/Exp3/")
```